version: "3.8"

services: 
    db:
        image: postgres:15.1
        restart: always
        volumes: 
            - ./pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - "5432:5432"

    app:
        build: .
        entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
        volumes:
            - ./src:/var/www/app
        environment: 
            - APP_ENV=local
            - APP_KEY=base64:tLmYfUrrZITzLIkSjFnV+PCAFxkdU+duUxjVSIlrrHo=
            - APP_DEBUG=true
            - DB_CONNECTION=pgsql
            - DB_HOST=db ## same as the database service name
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=example
        restart: unless-stopped
        ports: 
            - 8000:80
        depends_on:
            - db

volumes:
    db-data: